apiVersion: v1
kind: Service
metadata:
  name: orderswebappsvc
  labels:
        app: orderswebapp
spec:
  ports:
  - port: {{ .Values.ordersWebApp.servicePort }}
    targetPort: 8081
    protocol: TCP
  selector:
    app: orderswebapp